#!/bin/bash

tempName=`date +%Y%m%d%H%M%S%N_temp`

if [ ! -z "$1" ]; then
   backupName="$1"
else
   backupName=`date +%Y%m%d%H%M%S%N`
fi

backupFile="~/.sqlBackups/$backupName.sql"

echo backing up to $backupFile

mkdir -p ~/.sqlBackups

mysqldump -u root -p --all-databases --add-drop-database > ~/.sqlBackups/$tempName

if [ $? -eq 0 ]; then
  mv ~/.sqlBackups/$tempName ~/.sqlBackups/$backupName.sql
else
  rm ~/.sqlBackups/$tempName
fi
